### ISSUE TITLE
The driver fails to build on Linux kernel 6.15+

### ISSUE THREAD

**Issue by asemsem** [SimPilotAdamT/xmm7360-pci-SPAT#4]
error: implicit declaration of function ‘hrtimer_init’

This is due to upstream kernel changes where `hrtimer_init()` was replaced by `hrtimer_setup()`.

Suggested fix: I modified xmm7360.c:
```c
#if LINUX_VERSION_CODE < KERNEL_VERSION(6,15,0)
    hrtimer_init(&xn->deadline, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
#else
    hrtimer_setup(&xn->deadline, NULL, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
#endif
```
then rebuild with dkms again and every works again.

Many thanks for your efforts!

**Comment by Oualid33** [comment]
It works fine on Ubuntu kernel 6.17.0-14.
Thank you

**Comment by asemsem** [comment]
I am on zen kernel now. For kernels 6.18 and above, you will also need to edit _xmm7360_tty_write_ function variables from _int_ to _long int_  (around line 1286)

```
static long int xmm7360_tty_write(struct tty_struct *tty, const unsigned char *buffer, long unsigned int count)
{
	struct queue_pair *qp = tty->driver_data;
	int written;

	written = xmm7360_qp_write(qp, buffer, count);

	if (written < 0) {
		// Error occurred during write
		return written;
	}

	if (written < count) {
		qp->tty_needs_wake = 1;
	}

	return written;
}

```
> It works fine on Ubuntu kernel 6.17.0-14. Thank you

**Comment by stakan-web** [comment]
Hello!

Title: Fibocom L850‑GL (Intel XMM7360) on HP EliteBook 830 G8 – driver builds, wwan0 appears, but no tty ports and no SIM detection (Ubuntu 25.10, kernel 6.17.0‑19)

Hardware:
HP EliteBook 830 G8 (with HP Wolf Security / UEFI)
Modem: Fibocom L850‑GL (PCI ID 8086:7360) – same hardware as generic Fibocom module, but HP version may have different firmware.

System:
Ubuntu 25.10
Kernel 6.17.0‑19‑generic

What I tried:
Original xmm7360-pci – does not compile on 6.17+ (hrtimer errors).
Fork SimPilotAdamT/xmm7360-pci-spat – includes hrtimer patch.
Applied additional patch for xmm7360_tty_write (signature changed to long int and long unsigned int).
Fixed a typo: inside the function, buf was used but the parameter is buffer – replaced buf with buffer.

What works:
Module builds without errors.
Module loads (confirmed by lsmod):

> lsmod | grep xmm7360
> xmm7360                40960  0


ModemManager detect the modem:

> mmcli -L
>     /org/freedesktop/ModemManager1/Modem/0 [Fibocom] L850 LTE Module","L850



What does NOT work:
No tty devices (/dev/ttyXMM*):

> ls -l /dev/ttyXMM*
> crw-rw---- 1 root dialout 509, 0 Mar 26 08:36 /dev/ttyXMM0
> crw-rw---- 1 root dialout 509, 1 Mar 26 08:36 /dev/ttyXMM1
> crw-rw---- 1 root dialout 509, 2 Mar 26 08:37 /dev/ttyXMM2

The SIM is not initialized – AT commands cannot be sent.

Full kernel log for the driver:

> sudo dmesg | grep xmm
> [    5.542770] xmm7360: loading out-of-tree module taints kernel.
> [    5.542777] xmm7360: module verification failed: signature and/or required key missing - tainting kernel
> [    5.580998] xmm7360 0000:55:00.0: enabling device (0000 -> 0002)
> [    5.581748] xmm7360 0000:55:00.0: modem is ready
> [    5.617734] Modules linked in: intel_cstate(+) kfifo_buf(+) libarc4 videobuf2_v4l2 spi_intel_pci processor_thermal_wt_req hid_sensor_iio_common btmtk snd_timer ttm i2c_smbus iwlwifi mei_me videobuf2_common processor_thermal_power_floor wmi_bmof spi_intel pcspkr videodev xmm7360(OE+) industrialio i2c_mux drm_display_helper mei snd processor_thermal_mbox bluetooth soundcore cfg80211 cec intel_soc_dts_iosf rc_core mc i2c_algo_bit igen6_edac platform_profile intel_pmc_core int3403_thermal int340x_thermal_zone pmt_telemetry pmt_discovery pmt_class intel_hid sparse_keymap intel_pmc_ssram_telemetry int3400_thermal acpi_pad acpi_thermal_rel intel_vsec wireless_hotkey joydev input_leds mac_hid sch_fq_codel msr parport_pc ppdev lp parport efi_pstore nfnetlink dmi_sysfs ip_tables x_tables autofs4 btrfs blake2b_generic xor raid6_pq usbmouse usbkbd usbhid hid_sensor_hub intel_ishtp_hid ucsi_acpi typec_ucsi typec hid_multitouch hid_generic nvme intel_lpss_pci nvme_core serio_raw video intel_ish_ipc intel_lpss nvme_keyring
> [    5.617881]  xmm7360_net_setup+0x2c/0xc0 [xmm7360]
> [    5.617891]  ? __pfx_xmm7360_net_setup+0x10/0x10 [xmm7360]
> [    5.617895]  xmm7360_dev_init+0x2b1/0x360 [xmm7360]
> [    5.617899]  xmm7360_probe.cold+0x6d/0xec [xmm7360]
> [    5.617937]  ? __pfx_xmm7360_init+0x10/0x10 [xmm7360]
> [    5.617948]  ? __pfx_xmm7360_init+0x10/0x10 [xmm7360]
> [    5.617957]  xmm7360_init+0x115/0x130 [xmm7360


Network interface wwan0 appears (but no IP):


> ip link show wwan0
> 2: wwan0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000  link/none




The same modem hardware, as a generic Fibocom module, is often supported by the iosm driver in mainline kernels.
On this HP laptop, the iosm driver loads but creates no devices on kernel 6.17.
The community fork successfully provides the wwan0 interface, but the missing tty ports prevent AT command communication and proper SIM setup.

Possibly the HP firmware or UEFI (Wolf Security) requires a different initialization sequence.

Question:
Has anyone successfully created tty ports with this driver on HP EliteBook 830 G8 (or similar) with kernel 6.17?
What is needed to enable the tty devices and get SIM / modem manager working?
I am happy to test patches or provide additional logs.

Thank you for your work on this driver.
