### PR TITLE
Fix hrtimer_init() compilation error for kernel >= 6.15

### PR DESCRIPTION
**Pull request by singul4ri7y**
_**Title**_

### CODE REVIEW

**Comment by vitalibondar** [comment]
Ran into this on Arch, kernel 7.1.8. Current master fails with exactly one error:

```
xmm7360.c:1114:9: error: implicit declaration of function ‘hrtimer_init’
```

Applied this PR on top of 27c1b26: builds clean, module loads, modem comes up.

```
xmm7360 0000:05:00.0: modem is ready
```

Fibocom L850-GL in a ThinkPad T14s Gen 1, `/dev/xmm0/rpc` created as expected. Right now this is the only thing between master and a working build on 6.15+, so the driver won't compile out of the box on any current distro kernel.

Small nit, take it or leave it: the added lines are indented with spaces, the rest of the file uses tabs.
